### ISSUE TITLE
Player doesn't open sometimes

### ISSUE THREAD

**Issue by dundunn** [gustaebel/python-mpv#3]
So I want to create a lightweight frontend for Livestreamer and for that I wanted to use your implementation of mpv. 

I tested two mp3-files with example.py. I removed everything beyond line 77. 

The problem now is that the first mp3-file starts mpv like this:
![screen first podcast](https://i.imgur.com/KmNmVPO.png)

And the second like this:

![screen second podcast](https://i.imgur.com/SgmvPkh.png)

The first mp3-file doesn't show the mpv-interface, the second does. Could somebody help me understand this problem? 

Here's my console inputs and outputs: 

``` bash
#( 1.09.16@11:46 )( dun@Arch64L ):~/_workspace/py/python-mpv@master✗✗✗ python example.py /home/dun/Downloads/swr2wissen-20160829-mythos-milch.12844s.mp3
length in seconds: 2132.304
position: 0.025877
position: 0.133741
position: 0.198759
position: 0.248192
position: 0.31065
position: 0.376563
position: 0.441851
position: 0.508162
position: 0.574142
position: 0.629666
position: 0.695731
position: 0.761734
position: 0.827672
position: 0.894421
position: 0.961385
position: 1.028022
position: 1.094386
position: 1.160716
position: 1.227279
position: 1.338372
position: 1.405134
position: 1.471421
position: 1.538321
position: 1.605169
position: 1.672106
position: 1.7385
position: 1.805672
position: 1.872345
position: 1.939482
position: 2.005462
position: 2.072074
position: 2.138282
position: 2.204502
position: 2.270376
position: 2.336585
position: 2.402982
position: 2.469205
position: 2.535354
position: 2.601712
position: 2.667962
position: 2.733959
position: 2.800147
position: 2.866418
position: 2.933196
position: 3.000128
position: 3.066293
position: 3.132258
position: 3.198902
position: 3.264953
position: 3.330753
position: 3.396904
position: 3.463966
position: 3.530167
position: 3.596539
position: 3.663722
position: 3.730144
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
#( 1.09.16@11:47 )( dun@Arch64L ):~/_workspace/py/python-mpv@master✗✗✗ python example.py /home/dun/Downloads/mw052.mp3 
length in seconds: 5020.708571
position: 0.154082
position: 0.313354
position: 0.502217
position: 0.62872
position: 0.81869
position: 1.00921
position: 1.198504
position: 1.388247
position: 1.578254
position: 1.768782
position: 1.958318
position: 2.148605
position: 2.338216
position: 2.527754
position: 2.718365
position: 2.907559
position: 3.096897
position: 3.285606
position: 3.474963
position: 3.664202
position: 3.853558
position: 4.043647
position: 4.232778
position: 4.421981
position: 4.612354
position: 4.801346
position: 4.990769
position: 5.180468
position: 5.369266
position: 5.558145
position: 5.747485
position: 5.907908
position: 6.12795
position: 6.317097
position: 6.507238
position: 6.697293
position: 6.887492
position: 6.944207
position: 7.058686
position: 7.248936
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
#( 1.09.16@11:47 )( dun@Arch64L ):~/_workspace/py/python-mpv@master✗✗✗ 


```

**Comment by gustaebel** [comment]
This has nothing to do with python-mpv. The second mp3 file has embedded album cover art which is displayed during playback. The first mp3 has none which is why the mpv window is missing. If you want to prevent the album art from being displayed you can pass the `--audio-display=no` option to the mpv process.

**Comment by dundunn** [comment]
Thank you very much for that clarification! I wanted to know why there wasn't an interface. I thought it was a mistake.
